server:
  port: 6688

spring:
  application:
    name: my-prometheus
management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  metrics:
    tags:
      application: ${spring.application.name}