server:
  port: 8111
  httpPort: 8456
  httpsPort: 8111
  ssl:
    key-store: classpath:javaboy.p12
    key-store-password:  tomcat123456
    key-alias:  tomcathttps
  tomcat:
    max-threads: 2000
    max-connections: 20000